version: '3'
services:
  ds0:
    image: mysql:8.0
    container_name: mysql-0
    ports:
      - 10000:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --init-file=/data/application/init_ds0.sql
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init_ds0.sql:/data/application/init_ds0.sql
  ds1:
    image: mysql:8.0
    container_name: mysql-1
    ports:
      - 10001:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --init-file=/data/application/init_ds1.sql
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init_ds1.sql:/data/application/init_ds1.sql