version: '3'
services:
  db0:
    image: mysql:8.0
    container_name: mysql-0
    ports:
      - 10000:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --init-file=/data/application/init.sql
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/data/application/init.sql
  db1:
    image: mysql:8.0
    container_name: mysql-1
    ports:
      - 10001:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --init-file=/data/application/init.sql
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/data/application/init.sql